# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fcu_common/FW_Current_Path.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FW_Current_Path(genpy.Message):
  _md5sum = "4af1751f6b464a5a3cb09551a027be48"
  _type = "fcu_common/FW_Current_Path"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Current path output from the path manager, input to path follower

# @warning Va_d have always to be valid, r and q need to be valid if flag is true, c rho and lambda need to be valid otherwise
bool flag		# Inicates strait line or orbital path (true is line, false is orbit)
float32 Va_d		# Desired airspeed (m/s)
float32[3] r		# Vector to origin of straight line path (m)
float32[3] q		# Unit vector, desired direction of travel for line path
float32[3] c		# Center of orbital path (m)
float32 rho		# Radius of orbital path (m)
int8 lambda		# Direction of orbital path (clockwise is 1, counterclockwise is -1)

"""
  __slots__ = ['flag','Va_d','r','q','c','rho','lambda_']
  _slot_types = ['bool','float32','float32[3]','float32[3]','float32[3]','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flag,Va_d,r,q,c,rho,lambda_

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FW_Current_Path, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.flag is None:
        self.flag = False
      if self.Va_d is None:
        self.Va_d = 0.
      if self.r is None:
        self.r = [0.,0.,0.]
      if self.q is None:
        self.q = [0.,0.,0.]
      if self.c is None:
        self.c = [0.,0.,0.]
      if self.rho is None:
        self.rho = 0.
      if self.lambda_ is None:
        self.lambda_ = 0
    else:
      self.flag = False
      self.Va_d = 0.
      self.r = [0.,0.,0.]
      self.q = [0.,0.,0.]
      self.c = [0.,0.,0.]
      self.rho = 0.
      self.lambda_ = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Bf.pack(_x.flag, _x.Va_d))
      buff.write(_struct_3f.pack(*self.r))
      buff.write(_struct_3f.pack(*self.q))
      buff.write(_struct_3f.pack(*self.c))
      _x = self
      buff.write(_struct_fb.pack(_x.rho, _x.lambda_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.flag, _x.Va_d,) = _struct_Bf.unpack(str[start:end])
      self.flag = bool(self.flag)
      start = end
      end += 12
      self.r = _struct_3f.unpack(str[start:end])
      start = end
      end += 12
      self.q = _struct_3f.unpack(str[start:end])
      start = end
      end += 12
      self.c = _struct_3f.unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.rho, _x.lambda_,) = _struct_fb.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Bf.pack(_x.flag, _x.Va_d))
      buff.write(self.r.tostring())
      buff.write(self.q.tostring())
      buff.write(self.c.tostring())
      _x = self
      buff.write(_struct_fb.pack(_x.rho, _x.lambda_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.flag, _x.Va_d,) = _struct_Bf.unpack(str[start:end])
      self.flag = bool(self.flag)
      start = end
      end += 12
      self.r = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.q = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.c = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 5
      (_x.rho, _x.lambda_,) = _struct_fb.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_fb = struct.Struct("<fb")
_struct_Bf = struct.Struct("<Bf")
_struct_3f = struct.Struct("<3f")
