// Generated by gencpp from file opencv_stuff/MyImage.msg
// DO NOT EDIT!


#ifndef OPENCV_STUFF_MESSAGE_MYIMAGE_H
#define OPENCV_STUFF_MESSAGE_MYIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace opencv_stuff
{
template <class ContainerAllocator>
struct MyImage_
{
  typedef MyImage_<ContainerAllocator> Type;

  MyImage_()
    : imageId(0)
    , image()  {
    }
  MyImage_(const ContainerAllocator& _alloc)
    : imageId(0)
    , image(_alloc)  {
    }



   typedef uint8_t _imageId_type;
  _imageId_type imageId;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;




  typedef boost::shared_ptr< ::opencv_stuff::MyImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_stuff::MyImage_<ContainerAllocator> const> ConstPtr;

}; // struct MyImage_

typedef ::opencv_stuff::MyImage_<std::allocator<void> > MyImage;

typedef boost::shared_ptr< ::opencv_stuff::MyImage > MyImagePtr;
typedef boost::shared_ptr< ::opencv_stuff::MyImage const> MyImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_stuff::MyImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_stuff::MyImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opencv_stuff

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'opencv_stuff': ['/home/jaron/catkin_ws/src/opencv_stuff/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opencv_stuff::MyImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_stuff::MyImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_stuff::MyImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_stuff::MyImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_stuff::MyImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_stuff::MyImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_stuff::MyImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2344f5b8ab970a363dd7f4dc1ca716cb";
  }

  static const char* value(const ::opencv_stuff::MyImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2344f5b8ab970a36ULL;
  static const uint64_t static_value2 = 0x3dd7f4dc1ca716cbULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_stuff::MyImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_stuff/MyImage";
  }

  static const char* value(const ::opencv_stuff::MyImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_stuff::MyImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 imageId\n\
sensor_msgs/Image image\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::opencv_stuff::MyImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_stuff::MyImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imageId);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MyImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_stuff::MyImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_stuff::MyImage_<ContainerAllocator>& v)
  {
    s << indent << "imageId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.imageId);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_STUFF_MESSAGE_MYIMAGE_H
